### ISSUE TITLE
Babel

### ISSUE THREAD

**Issue by wenom64** [tajo/javascript#10]
Mám dotaz na tento kód:

``` javascript
// lib/mathplusplus.js
export * from "lib/math";
export var e = 2.71828182846;
export default function(x) {
    return Math.exp(x);
}
```

Proč je "export \* from" neměl by tam být import? (Koukal jsem, že to tak je i v oficiální dokumentaci.)

**Comment by tajo** [comment]
Jde o validni zapis - re-exporting. `export * from "lib/math"` prida exporty z `lib/math` do stavajiciho modulu. Nicmene zatim jsem to nikdy nepouzil / nepotreboval.
