### ISSUE TITLE
notifu.exe

### ISSUE THREAD

**Issue by hxpro** [tajo/javascript#11]
ClamAV mi nahlásil že našel Win.Worm.Chir-2815 v souboru notifu.exe, máte někdo tucha proč?

`javascript/examples/dev-stack/node_modules/node-notifier/vendor/notifu/notifu.exe: Win.Worm.Chir-2815 FOUND`

**Comment by tajo** [comment]
Sleduj: https://github.com/mikaelbr/node-notifier/issues/86

**Comment by hxpro** [comment]
aha, ok, dík...
