### ISSUE TITLE
Pokračování?

### ISSUE THREAD

**Issue by pavel-sindelka** [tajo/javascript#16]
Ahoj, chtěl bych se zeptat, jestli plánuješ v seriálu o Reactu pokračovat a pokud ano, tak kdy. :) Velice se mi tvoje články líbí a chtěl bych se dozvědět více o Reduxu.

**Comment by tajo** [comment]
Pokračování neplánuju. Ad Redux: Nechce se mi překládat jejich už výbornou dokumentaci: http://redux.js.org/ :)

**Comment by lspdv** [comment]
To je ale velka skoda, myslim si, ze to cte hodne lidi. :(
